import {
  alternatingCase,
  camelCase,
  capitalize,
  constantCase,
  kebabCase,
  lowercase,
  normalizeSpaces,
  pascalCase,
  removeSpaces,
  snakeCase,
  slugify,
  titleCase,
  trim,
  uppercase,
} from "@/modules/text-transformer/domain/transform-text";

export const textTransformerUseCase = {
  uppercase,
  lowercase,
  capitalize,
  titleCase,
  trim,
  removeSpaces,
  normalizeSpaces,
  slugify,
  camelCase,
  pascalCase,
  snakeCase,
  kebabCase,
  constantCase,
  alternatingCase,
};
